name: MySQL Installation

on:
  pull_request:
    branches: [main]

jobs:
  install-mysql:
    name: Install MySQL
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_DIALECT: ${{ secrets.DB_DIALECT }}
      DB_POOL_MAX: ${{ secrets.DB_POOL_MAX }}
      DB_POOL_MIN: ${{ secrets.DB_POOL_MIN }}
      DB_POOL_ACQUIRE: ${{ secrets.DB_POOL_ACQUIRE }}
      DB_POOL_IDLE: ${{ secrets.DB_POOL_IDLE }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

    steps:
    - name: Start MySQL
      run: |
        sudo systemctl start mysql

    - name: Create DATABASE
      run: |
        sudo mysql -h ${{ env.DB_HOST }} -u root -p"${{ env.MYSQL_ROOT_PASSWORD }}" -e "CREATE DATABASE IF NOT EXISTS ${{ env.DB_NAME }};"
        sudo mysqladmin -u root -p"${{ env.MYSQL_ROOT_PASSWORD }}" password "${{ secrets.DB_PASSWORD }}"

    - name: Verify MySQL connection
      run: |
        mysql -h ${{ env.DB_HOST }} -u ${{ env.DB_USER }} -p"${{ env.DB_PASSWORD }}" -e "SHOW DATABASES;"
