name: MySQL Installation

on:
  push:
    branches:
      - main

jobs:
  install-mysql:
    name: Install MySQL
    runs-on: ubuntu-latest

    steps:
      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install mysql-server -y
