name: MySQL Installation

on:
  pull_request:
    branches: [main]

jobs:
  install-mysql:
    name: Install MySQL
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_DIALECT: ${{ secrets.DB_DIALECT }}
      DB_POOL_MAX: ${{ secrets.DB_POOL_MAX }}
      DB_POOL_MIN: ${{ secrets.DB_POOL_MIN }}
      DB_POOL_ACQUIRE: ${{ secrets.DB_POOL_ACQUIRE }}
      DB_POOL_IDLE: ${{ secrets.DB_POOL_IDLE }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Start MySQL
      run: |
        sudo systemctl start mysql

    - name: Create Database
      run: |
        sudo mysql -u root -p"${{ secrets.MYSQL_ROOT_PASSWORD }}" -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_NAME }};"
    
    - name: Alter MySQL Root Password
      run: |
        sudo mysqladmin -u root -p"${{ secrets.MYSQL_ROOT_PASSWORD }}" password "${{ secrets.DB_PASSWORD }}"

    # - name: Create Database User
    #   run: |
    #     sudo mysql -u root -p"${{ secrets.MYSQL_ROOT_PASSWORD }}" -e "GRANT ALL PRIVILEGES ON ${{ secrets.DB_NAME }}.* TO '${{ secrets.DB_USER }}'@'%';"

    - name: Verify MySQL connection
      run: |
        mysql -u ${{ secrets.DB_USER }} -p"${{ secrets.DB_PASSWORD }}" -e "SHOW DATABASES;"
    
    - name: Install dependencies
      run: npm install
      
    - name: Runs Tests
      run: npm run test


    - name: Execute exit 1 for failure testing
      if: failure()
      run: exit 1