name: MySQL Installation

on:
  pull_request:
    branches: [main]

jobs:
  install-mysql:
    name: Install MySQL
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_DIALECT: ${{ secrets.DB_DIALECT }}
      DB_POOL_MAX: ${{ secrets.DB_POOL_MAX }}
      DB_POOL_MIN: ${{ secrets.DB_POOL_MIN }}
      DB_POOL_ACQUIRE: ${{ secrets.DB_POOL_ACQUIRE }}
      DB_POOL_IDLE: ${{ secrets.DB_POOL_IDLE }}


    steps:
    - name: Install MySQL
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server
        sudo systemctl start mysql


    - name: Setup MySQL
      run: |
        sudo mysql -e "CREATE DATABASE IF NOT EXISTS ${{ env.DB_NAME }};"
        sudo mysql -e "ALTER USER '${{ env.DB_USER }}'@'localhost' IDENTIFIED BY '${{ env.DB_PASSWORD }}';"
        sudo mysql -e "GRANT ALL PRIVILEGES ON ${{ env.DB_NAME }}.* TO '${{ env.DB_USER }}'@'localhost';"
        sudo mysql -e "FLUSH PRIVILEGES;"

    - name: Verify MySQL connection
      run: |
        mysql -u ${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} -e "SHOW DATABASES;"
