name: Node.js CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: integration
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
