name: Packer Validate
 
on:
  pull_request:
    branches: [main]
 
jobs:
  build:
    name: Packer-Validate
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up GCP Credentials
      run: |
        echo "${{ secrets.gcp_service_account_credentails }}" > gcp_credentials.json
      env:
        gcp_service_account_credentails: ${{ secrets.gcp_service_account_credentails }}
 
    - name: Install Packer
      run: |
        if ! command -v packer &> /dev/null
        then
            curl -O https://releases.hashicorp.com/packer/1.7.4/packer_1.7.4_linux_amd64.zip
            unzip packer_1.7.4_linux_amd64.zip
            sudo mv packer /usr/local/bin/packer
        fi
        packer --version
 
    - name: create artifact
      run: |
        zip -r webapp.zip ./
 
    - name: Initialize Packer
      run: packer init packer/packer.pkr.hcl
    
    - name: Check Formatting
      run: |
        if !packer fmt -check packer/packer.pkr.hcl; then
          echo "Invalid packer format"
          exit 1
        fi
 
    - name: Validate Packer Template
      run: packer validate -var 'gcp_credentials_file=gcp_credentials.json' packer/packer.pkr.hcl